import sys
from main.data_loader import load_dataset
from main.llm_interface import ask_about_data

"""
Command-line interface for interacting with the dataset using a local LLM.
Loads the dataset, prompts the user for questions, and prints the model’s answers.
"""

# Main loop that loads the dataset, accepts user questions,
# and displays answers generated by the LLM.

if __name__ == '__main__':
    try:
        df = load_dataset()
    except Exception as e:
        print("Failed to load dataset:", e)
        sys.exit(1)

    while True:
        try:
            question = input("Ask a question about this dataset...")
            if question in ['quit', 'exit']:
                print("Goodbye!")
                break

            if not question.strip():
                print ("Question cannot be empty.Exiting...")
                sys.exit(1)

            answer = ask_about_data(df, question)

            print("\nLLM's Answer: ")
            print(answer)

        except ConnectionError:
            print("Could not connect to the LLM. Make sure Ollama is running.")
            sys.exit(1)

        except Exception as e:
            print("An unexpected error occurred:", e)
            sys.exit(1)

