services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    container_name: ollama
    restart: unless-stopped
    networks:
      - hurricane_network
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 10s
      timeout: 5s
      retries: 5

  flask_app:
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - "5001:5000"
    networks:
      - hurricane_network
    depends_on:
      ollama:
        condition: service_healthy  # Ensures Ollama is healthy before Flask starts
    entrypoint: ["/wait-for-ollama.sh"]
    environment:
      - OLLAMA_URL=http://ollama:11434
volumes:
  ollama:

networks:
  hurricane_network:
